name: app

services:
  shop:
    container_name: shop
    image: ${IMAGE:-ghcr.io/abdullayevbahrom/shop-php:8.3-fpm-alpine3.20}
    platform: linux/amd64
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    working_dir: /var/www/html
    tty: true
    environment:
      YII_ENV: prod
      YII_DEBUG: "false"
    ports:
      - "127.0.0.1:${HTTP_PORT:-8001}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/supervisor/conf.d/nginx.conf:/etc/supervisor/conf.d/nginx.conf
      - ./docker/supervisor/conf.d/php-fpm.conf:/etc/supervisor/conf.d/php-fpm.conf
    depends_on:
      - db

  db:
    container_name: mysql
    image: "mariadb:10.5.2"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-password}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE:-shop}"
      MYSQL_USER: "${DB_USERNAME:-shop}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-password}"
      TZ: Asia/Tashkent
    ports:
      - "127.0.0.1:${DB_PORT:-3306}:3306"
    volumes:
      - "db_data:/var/lib/mysql"
      # - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

volumes:
  db_data:
    driver: local
