name: "app"

services:
  shop:
    container_name: shop
    build:
      context: ./docker
      dockerfile: Dockerfile-dev
      args:
        - PUID=${PUID:-1000}
        - PGID=${PGID:-1000}
    restart: unless-stopped
    working_dir: /var/www/html
    tty: true
    ports:
      - 127.0.0.1:${HTTP_PORT:-8002}:80
    environment:
      TZ: Asia/Tashkent
      DB_HOST: app-market-backend-db-1
      DB_NAME: app
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ""
      EIMZO_SERVER_URL: http://eimzo-server:8080
    volumes:
      - ./:/var/www/html:rw
      - ./docker/supervisor:/etc/supervisor
    depends_on:
      - eimzo-server
      - rabbitmq

  rabbitmq:
    container_name: app-rabbitmq
    image: rabbitmq:3.13-management-alpine
    restart: unless-stopped
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      TZ: Asia/Tashkent
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  eimzo-server:
    container_name: eimzo-server
    image: amazoncorretto:8-alpine3.19-jre
    restart: unless-stopped
    working_dir: /opt/eimzo
    command: >
      java -Dfile.encoding=UTF-8 -jar e-imzo-server.jar config.properties
    environment:
      TZ: Asia/Tashkent
    volumes:
      - ./docker/eimzo-server:/opt/eimzo:rw

volumes:
  rabbitmq_data: