FROM php:8.3-fpm-alpine3.20 AS base

ARG PUID=1000
ARG PGID=1000

RUN apk add --no-cache \
  nginx \
  curl \
  git \
  supervisor \
  zlib-dev \
  oniguruma-dev \
  bash \
  zip \
  libzip-dev \
  icu-dev \
  shadow \
  openssl-dev \
  freetype-dev \
  libjpeg-turbo-dev \
  libpng-dev \
  tzdata \
  && apk add --no-cache --virtual .build-deps \
  build-base \
  autoconf \
  linux-headers \
  && pecl install -o -f redis \
  && docker-php-ext-enable redis \
  && docker-php-ext-configure gd --with-freetype --with-jpeg \
  && docker-php-ext-configure intl \
  && docker-php-ext-install \
  gd \
  intl \
  pdo_mysql \
  mbstring \
  pcntl \
  opcache \
  zip \
  && groupmod -o -g ${PGID} www-data \
  && usermod -o -u ${PUID} -g www-data www-data \
  && apk del .build-deps \
  && rm -rf /tmp/pear /var/cache/apk/* \
  && mkdir -p /etc/supervisor/conf.d

ENV TZ=Asia/Tashkent
COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY docker/php/opcache.ini /usr/local/etc/php/conf.d/opcache.ini
COPY docker/php/php.ini /usr/local/etc/php/php.ini
COPY docker/php/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY docker/supervisor/supervisord.conf /etc/supervisor/supervisord.conf

WORKDIR /var/www/html

ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]