[program:rabbitmq-consumer]
command=/usr/local/bin/php /var/www/html/yii rabbit/consume-market-sync
process_name=%(program_name)s
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
startsecs=3
startretries=5
exitcodes=0,2
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
loglevel=info
